---
language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache/Cypress
script:
  - yarn verify
  - yarn start & yarn wait
  - yarn test
